### PR TITLE
Remove dissappeared

### LINKED ISSUE #3: `Dissappeared` exception is never caught
When using `WeakNode`, `pop_min_nonempty` can raise a `Disappeared` exception. This exception is never caught...

Possible solutions:
1. Export the exception and specify document which functions can raise it.
2. Get rid of `pop_min_nonempty` and just have `pop_minimum` be recursive and return an option type (slight performance loss as the recursive case must now built/destruct options).
3. Add a try catch to `pop_minimum`, but I feel this would lose the performance benefit of using `pop_min_nonempty`

I'm personally in favor of option 2, @mlemerre thoughts ?

### PR DESCRIPTION
**Pull request by dlesbre**
Fixes #3.

### CODE REVIEW

**Comment by mlemerre** [comment]
Have eventually looked at the version with internal exceptions to see if it improved execution?

**Comment by mlemerre** [comment]
https://ocaml.org/docs/error-handling says that "However, exceptions have the great merit of being compiled into efficient machine code. When implementing trial and error approaches likely to back-track often, exceptions can be used to achieve good performance." which seems to be describing our situation

**Comment by dlesbre** [comment]
I've [tested it on godbolt](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyah04tvXIrGqIgSHVmmAMLp6AVzZMDTgDIEmbAA5TwAjbFIQAFZyAAd0JWJ7JlcPLwN4xLshf0CQtnDImOtsW2SRIhZSIlTPbx4rbBtspgqqolzgsIjoq0rq2vSGpX6OgK6CnqiASit0d1JUTi4iAE9Y7ABqIlJsLYBSAGYAEX2tAEFNzf2AdmdN3DZYtbPL67vN32wWGk30X4CRFeV1u9yCWC2/22uy2ACpoXtXq9sOols9kpsAJJKR7PVZIi6MIibXaoTZ0JiYAD6bAC1xO5PcTDKQmB73uuLWmwAtEdcJtwYE2aDPt8ATy%2BZsROgOJsIARyA8nmtpsKPuCcHKFZtdNMJYdcGyrps2CwiKgkOSAtTaUxNgRNgB3YhII0g9VCLa8g1Wyk0um6N3sqUyrYQNiKoh67386Wy8OKjVhoiK3XTLizejcKL8bxcHTkdDcADyznY9E2SnmiwOACZDnxyERtBnZgBraJaQzcaT8Nid8h5gtFrj8JQgLvN/MZ8hwWAoDA4fDEMiUah0RisDjcRuCYRiCScGRyYTKNSaafkfS1wzGUzmSwlFneCBOQbeQ43vzjfKFKSyTIkiEd8QE/OIEiAphOl/HpjyfFo2gGNw6lAm94PKUZoO6SI4NGECwJGdosMmHDpFmKsFiWbg1g2BEDhONUOWVfELnde4vh%2BP4AWERiBQhLi6M2eEdkRC5kVRbB0SELEcWYglziJElSl9G06SOY5GWZFpeM5VZ9X5UgWAIFQZN03iOPFGMtUVXTVVY4Mk2snVoz5INTXNS0KVUu0HWdIhXXs40RRRNEWlM5j9JU/07UDQK2LlCNthcn1EsciAU2cmcsy4HNBxbQsSzLCxK2rJZrnrWt%2BCnHRplmJBvhwSIIEzHs%2BwHId%2BBHMcJybFtavIDtpAADgAOgANh4G5pAmw4omketpBuBpssOXN8q63rp1mOdkBAQgaBoNdaHkA9JGPPdFBUDR8voJBx2Wu79poGjOC7W6VHUHYWHQKS834Ug7pAG8AaUJ6Xp6kGUS%2Bn6Wm4LLszWy8R2OAgDs2AA1AhsEdCJNnUIaxu5MbpD%2BB8Yc2aQRpkEatE2AA3JQ8YJomSbMctycp6mC2qmcIAXGVYgYCIjowJ4hciNmLGkGQuw3IgInHCBQny0IAiqVYd34VXWFIVZi1CXRSinRtRY4YRiyYegNcvHBQncYAy3oehx14fgcFNExJBtghSTsOnsBdgsUVKdx5c1yhhCaG6CFCQzddcHB8p2Ah%2B1d8h/dIUIEmwY5sA94B6ACUAtoEIxgCUTHseLDY813E7xDO2QLrPa7L30Za7xASXLEL0Jx0gWYYeSF3Ooz0gCBwfvmsaZpkkcSkQIab88mwjIIJaRfwKyZJiL/YYmiNjD2k39ChEQsYV5IgxCKQtJ6j6Iif1XnhyNKo8WpyxHh24JnCeJ0n2bPAplTSmtMIDLhIKQcqDZ0ybRqrOfmYtGAUCoBAUWgtkFdwfNLaQssGDy1IIrZWl5tbq3DqQ3W%2BtDa2HDqbZgRALZW3yrbe2jtnbh3dneL2BZCC%2BwIP7QO/Bg6oFDssRsgIo6Xl7nHVYCdljc3HqnRsGcs4qFzvnQuJg%2BqlxYOXSujpq7MHDhdU6R4m7yBbheAs15bxaO7oYGOU9B6/RHoWMeE8A7wHIgfZ888XDISGOQZeEw95b0gpvQCLRd6wRnofM%2BeEAn31Pq0TCT8r7DASXfa%2BqTL571fpRTgtYP65Q6gVLgv8WYAIsBzEBNM5QQLINAopVU%2BrtmiDwEahwhq1iiF04mUQbhjSiLWAAnLIbKvY8pIzhlYHqPN%2BrZUqlM7%2Bo44GtnTgrOe0ggA) and didn't find that big of a difference between the two.

**Comment by mlemerre** [comment]
Thanks, interesting!

**Pull request merged**
